event_names: list = [
    "APP_STARTUP",
    "READ_STORY",
    "REFLECTION_ANSWERING_START",
    "REFLECTION_PLAYBACK_START",
    "CHALLENGE_PICKED",
    "GEOSTORY_VIEWED",
    "GEOSTORY_SUBMITTED",
    "EMOTION_LOGGED"
]