# Generated by Django 3.0.2 on 2020-01-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('app_start_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(default=0)),
            ],
        ),
    ]
