# Generated by Django 3.0.3 on 2020-04-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
